// wallet connection states
export const INITIAL = "INITIAL"
export const PERMISSIONS_GIVEN = "PERMISSIONS_GIVEN"
export const ESTABLISHING_CONNECTION = "ESTABLISHING_CONNECTION"
export const ACCOUNT_ACTIVE = "ACCOUNT_ACTIVE"
export const DISCONNECTED = "DISCONNECTED"
export const CONNECTION_ERROR = "CONNECTION_ERROR"